spring.application.name=Springpro
spring.jpa.show-sql=true

server.port=8080

spring.datasource.url=jdbc:mysql://localhost/goutham_sql

spring.datasource.driverClassName=com.mysql.jdbc.Driver

spring.datasource.username=root

spring.datasource.password=Rajan#321
